source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

target 'CRToastDemo', :exclusive => true do
    pod 'CRToast', :path => "../"
end

target 'CRToastTests', :exclusive => true do
   pod 'CRToast', :path => "../"
end

target 'Acceptance Tests', :exclusive => true do
  pod 'KIF', '~> 3.0'
end
