language: objective-c
os: osx
osx_image: xcode10.3
env:
  matrix:
    - TEST_TYPE=iOS
    - TEST_TYPE=CocoaPods
    - TEST_TYPE=Carthage
install:
- |
  if [ "$TEST_TYPE" = "iOS" ]; then
    gem install xcpretty -N --no-ri --no-rdoc
    gem update cocoapods
  elif [ "$TEST_TYPE" = Carthage ]; then    
    brew install carthage || brew upgrade carthage
  fi
script:
- |
  if [ "$TEST_TYPE" = "iOS" ]; then
    set -o pipefail
    xcodebuild test -project CRToast.xcodeproj -scheme CRToast -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 4s" -destination "platform=iOS Simulator,name=iPhone 6 Plus" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c
    pushd Example
      xcodebuild -project CRToastDemo.xcodeproj -scheme CRToastDemo -sdk iphonesimulator | xcpretty -c
    popd
  elif [ "$TEST_TYPE" = CocoaPods ]; then
    pod lib lint CRToast.podspec
    pod lib lint --use-libraries CRToast.podspec
  elif [ "$TEST_TYPE" = Carthage ]; then
    carthage build --no-skip-current
  fi
# after_success:
# - |
#   if [ "$TEST_TYPE" = "iOS" ]; then
#     bash <(curl -s https://codecov.io/bash)
#   fi
